version: '3.1'

networks:
  net:

services:
  app:
    image: socket-chat
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - app
