version: '3.1'

networks:
  net:

services:
  app:
    image: socket-chat
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - app

  nginx:
    image: nginx
    command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      net:
        aliases:
          - nginx

